### ISSUE TITLE
运行GUI.py 时抛出异常

### ISSUE THREAD

**Issue by lteyox** [xiaoWangSec/jx-qndxx#10]
**运行GUI.py 时抛出异常 无法打开GUI界面**
```python
Traceback (most recent call last):
  File "c:\Users\lteyo\Desktop\jx-qndxx-master\GUI.py", line 186, in <module>
    readdata(tree)
  File "c:\Users\lteyo\Desktop\jx-qndxx-master\GUI.py", line 90, in readdata
    userlist = getDataFromFile()
NameError: name 'getDataFromFile' is not defined
```
![image](https://github.com/xiaoWangSec/jx-qndxx/assets/57826838/a804145c-0259-459a-baf1-fce14c0454fa)

添加后解决 不知是否是个例
```python
def getDataFromFile():
    with open("users.json", 'r', encoding='utf-8') as reader:
        data = json.load(reader)
    return data
```

**Comment by xiaoWangSec** [comment]
原因竟是忘了push本地代码
现已更新https://github.com/xiaoWangSec/jx-qndxx/blob/master/appletYouthStudy.py#L21
